# ─── Aplicación ───────────────────────────────────────────────────────────────
spring.application.name=servicio-descubrimiento
server.port=8761

# ─── Eureka Server ────────────────────────────────────────────────────────────
# Evita que el servidor intente registrarse a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Mensaje de bienvenida en el dashboard
eureka.instance.hostname=localhost
eureka.server.enable-self-preservation=false
